---
title: "Projects"
# listing:
#   contents: adaptation
#     # - "bos_uhi.ipynb"
#     # - "*.ipynb"
# #   exclude: 
#     # - "Projects/adaptation/sovi_svi.ipynb"  
#   type: grid
#   grid-columns: 3
#   grid-item-border: true
#   grid-item-align: center
#   image-height: 150px
#   sort-ui: False
#   filter-ui: False
#   sort:
#     - "date asc"
---


### ❏ Boston: The Green Space, Blue Space, and Urban Heat Island

#### Summary:
In this study, I explore the mitigating effects of green and blue spaces on Urban Heat Islands (UHIs) in Boston. This research is driven by the growing concern over UHIs, where urban areas experience higher temperatures than their rural counterparts, exacerbating heatwaves. Boston, with its rich mix of historical, commercial, and natural landscapes, serves as an ideal case study for assessing how parks, rivers, and the ocean contribute to cooling urban environments. My findings aim to provide actionable insights for urban planning, emphasizing the critical role of integrating green and blue spaces in urban settings to combat the UHI effect.

#### Methodology:
I adopted a methodology that combines Landsat8 satellite imagery and GIS data to assess the relationship between the proximity and size of green and blue spaces and urban temperatures in Boston. By drawing from and adapting the methodology of Park Jong-Hwa & Cho Gi-Hyoug (2016), my study specifically focuses on Land Surface Temperature (LST) as the quantifiable measure of UHIs. Notably, I excluded Digital Elevation Model (DEM) data due to Boston’s relatively flat terrain and instead emphasized the importance of proximity to water bodies. Variables such as Land Use, NDVI, NDBI, and Albedo were controlled to isolate their effects on urban temperatures. My approach involves processing Landsat 8 satellite imagery to derive environmental indicators and reclassifying land use within Boston to understand how urban green and blue spaces impact urban heat.

#### Results and Implications:
The results reveal that both proximity to and the size of parks and water bodies significantly correlate with lower urban temperatures, thus mitigating the UHI effect in Boston. Specifically, the research highlights that larger parks and closer proximity to water bodies are associated with cooler urban areas. These findings underscore the intrinsic value of urban nature in mitigating heat islands and provide a compelling argument for urban planners to incorporate more green and blue spaces in cities. By demonstrating the cooling effects of these natural spaces, my study contributes to a broader understanding of sustainable urban planning practices aimed at combating the adverse effects of urban heat, offering a blueprint for other cities facing similar challenges.


[Visit the Story Map](https://arcg.is/0nLrHy)
<iframe src="https://arcg.is/0nLrHy" width="800" height="600" frameborder="0" allowfullscreen></iframe>



---

### ❏ Grid Vulnerability Index (GVI) - New York and Beyond

#### Summary:

The Grid Vulnerability Index (GVI) is a framework that combines real-time weather data with key power grid infrastructure components (power plants, transmission lines, and critical societal infrastructures) to dynamically assess grid stability. Using a hierarchical hexagonal grid system (H3) for spatial analysis, the GVI captures and integrates data at varying resolutions, enabling detailed local and regional analyses. Each component is assigned a vulnerability score based on factors such as energy source, capacity, length, and real-time weather conditions. The resulting index provides a granular visualization of grid vulnerability across New York State, with potential for expansion to a national level.

#### Methodology:


The GVI methodology involves data collection from diverse sources, including the U.S. Energy Information Administration (EIA) for power plant and transmission line data, the United States Geological Survey (USGS) for critical infrastructure data, and NOAA's Weather API for real-time weather conditions. Scoring algorithms consider factors like energy source, installed capacity, transmission line length, and the criticality of infrastructures during power outages. Weather conditions are scored based on their potential impact on grid operations, considering factors like temperature, dewpoint, wind speed, and humidity. These individual scores are then aggregated into a final GVI score for each grid cell.


#### Results and Implications

Analysis of the GVI results revealed spatial clusters of high vulnerability, particularly in densely populated areas and regions with aging infrastructure. These findings have significant implications for grid resilience planning and investment. The GVI can inform decisions regarding infrastructure upgrades, emergency preparedness, and resource allocation during extreme weather events. The dynamic nature of the index allows for real-time updates, enabling utilities and policymakers to respond proactively to evolving threats and mitigate potential disruptions to the power grid.




[Visit the Story Map](https://arcg.is/1i1XGP0)
<iframe src="https://arcg.is/1i1XGP0" width="800" height="600" frameborder="0" allowfullscreen></iframe>




---


### ❏ Spatial Statistics on Land Surface Temperature in Seoul


#### Summary:
This project aims to understand the spatial distribution of land surface temperature in the Seoul Metropolitan Area, focusing on the interaction between urbanization patterns, vegetation cover, and topography. A significant aspect of my work involved employing a suite of spatial and non-spatial statistical tools such as Moran’s I, Spatial Lag, and Spatial Error model to analyze the data, taking into account the spatial clustering of variables and their impact on urban heat.

#### Methodology:
Spatial Statistical Analysis
Started with the computation of Moran’s I to detect spatial autocorrelation in land surface temperature, confirming the presence of spatial clustering.
Applied a linear regression model to identify the relationship between temperature and predictors such as tree coverage, built-up areas, and altitude, without considering spatial dependencies.
Performed Moran’s I on residuals from the linear regression model to test for unaccounted spatial autocorrelation, indicating the need for spatially explicit models.
Implemented Spatial Lag Model and Spatial Error Model to incorporate spatial dependencies directly into the regression analysis, enhancing the model’s explanatory power.
Model Evaluation and Selection
Utilized the Akaike Information Criterion (AIC) and Log-Likelihood Values to compare model fit and complexity, guiding the selection of the most appropriate model.
Applied Lagrange Multiplier tests to diagnose and decide between spatial lag and spatial error models, ensuring the chosen model best represented the spatial processes influencing temperature distribution.

#### Results & Implications:
The analysis demonstrated that spatially explicit models offer superior insights into the factors driving land surface temperature patterns.
The findings advocate for the integration of green infrastructure in urban planning as a strategy to counteract the urban heat island effect.


[Download PDF](https://raw.githubusercontent.com/gigisung0503/spatial_statistics/main/05.%20Final%20Project/Final%20Project.pdf)

{{< pdf pdf/spatial_statistics.pdf width=100% height=800 >}}



---

### ❏ ETL and EDA for Internal Migration Analysis

#### Summary: 
Conducted an exploratory data analysis (EDA) and developed an ETL pipeline to analyze U.S. Population Migration data, aiming to derive a “Internal Migration” signal indicative of residential market demand. This project involved data manipulation, analysis, and visualization to uncover patterns of internal migration at the county level.

#### Technical Details:
ETL Process: Designed and implemented an ETL pipeline to extract data from various formats and years, which are provided by Internal Revenue Service(IRS). Transformed the data by cleaning and standardizing it, and loaded the processed data for analysis.
EDA: Employed statistical and visual analysis techniques to explore migration trends, identify high migration areas and anomalies, and calculate net migration flows. Utilized Python libraries such as GeoPandas for data manipulation, Plotly and Plotly Express for interactive visualizations, and seaborn for statistical plots.

#### Impact: 
The analysis provided insights into potential hotspots for residential market demand. The pipeline helped build a new location signal “Internal Migration.” This project highlights my ability to handle complex datasets and extract actionable insights. 

[Download EDA Notebook](https://raw.githubusercontent.com/gigisung0503/climate_migration/main/ETL_EDA/EDA_migration.ipynb)
<iframe src="https://nbviewer.jupyter.org/github/gigisung0503/climate_migration/blob/main/ETL_EDA/EDA_migration.ipynb?flush_cache=true" style="width: 100%; height: 800px; border: none;"></iframe>


[Download ETL Notebook](https://raw.githubusercontent.com/gigisung0503/climate_migration/blob/main/ETL_EDA/ETL_migration.ipynb)
<iframe src="https://nbviewer.jupyter.org/github/gigisung0503/climate_migration/blob/main/ETL_EDA/ETL_migration.ipynb?flush_cache=true" style="width: 100%; height: 800px; border: none;"></iframe>


---

### ❏ Economic Momentum Indicator


#### Summary:
In this exercise, I evaluated the economic strength and potential of various locations to withstand climate-related challenges. This indicator is vital for understanding how regions can either mitigate or amplify the impacts of climate events through robust economic foundations. Key metrics integrated into this indicator include employment rates, median income, house prices, and education levels, along with dynamic measures like the income-to-house-price ratio to assess housing affordability. The indicator’s effectiveness was validated by its correlation with returns from five types of real estate, providing deep insights into local economic trends and their broader implications.

#### Methodology:
I conducted a spatial analysis of economic metrics (e.g., employment, income, education) across CBSAs, incorporating dynamic measures, such as changes in employment rates, median income levels, and educational attainment over time. This allowed me to capture not just the current economic health of an area but also its trajectory. To validate my approach, I modeled and correlated these metrics with real estate returns across property types, using data from the ACS, FHFA, and NCREIF. I calculated and scaled various ratios (e.g., education level, employment, and income-to-house-price) and aggregated them into composite economic momentum scores. Correlation analyses were then used to examine the relationship between these scores and real estate returns, and the geographic distribution of scores was analyzed to identify leading and lagging counties.

#### Results & Implications:
The analysis of Economic Momentum Values highlighted significant spatial variability, with top-performing counties demonstrating robust economic indicators. I observed distinct geographical patterns, with notable differences between southeast and northeast states. The correlations between economic indicators and returns from different property types varied, revealing the nuanced nature of economic vitality and real estate performance. The insights from the Economic Momentum Indicator can guide policymakers and investors in making informed decisions to enhance resilience and optimize investments in diverse economic landscapes.

{{< pdf pdf/ws_EconomicMomentumWhitepaper.pdf width=100% height=800 >}}


<!-- Explore our diverse range of documents and notebooks: -->









<!-- <iframe src="https://kepler.gl/#/demo?mapUrl=https://raw.githubusercontent.com/gigisung0503/archive/04d6fcfe9509666d2c0c84d2d129462ec43587eb/misc/svi_west.json" style="border:0px #ffffff none;" name="myiFrame" scrolling="no" frameborder="0" marginheight="0px" marginwidth="0px" height="600" width="1000" allowfullscreen></iframe>
*<A map showing CDC's Social Vulnerability Index>* -->

<!-- <iframe src="https://kepler.gl/#/demo?mapUrl=https://dl.dropboxusercontent.com/scl/fi/i86u36dotdcvxn7v92gv5/svi_national.json?rlkey=q1q9m7houco9ku21cl6c2olsg&dl=1" style="border:0px #ffffff none;" name="myiFrame" scrolling="no" frameborder="0" marginheight="0px" marginwidth="0px" height="600" width="1000" allowfullscreen></iframe> -->


<!-- This section showcases my research and work on climate change, urban planning, and sustainable development. The topics covered in this section are cross-cutting and can be applied to various sectors and scales. The aim is to provide a comprehensive overview of the key issues, concepts, and strategies related to those topics. Also, I will share my thoughts on the latest trends, challenges, and opportunities in the field. -->
