project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Gigi Sung's Workspace"
  site-url: "https://gigisung0503.github.io/" 
  repo-url: https://github.com/gigisung0503/gigisung0503.github.io.git
  repo-actions: [source]

  page-footer:
    right: "All rights reserved. 2024."
    left: "&copy; CC-Gigi Sung, 2024"
  
  google-analytics: "G-EPVTNRSWSE"


  navbar:
    background: '#FFFFFF'
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - about.qmd
      - text: "Projects"
        file: ./Projects/index.qmd
      - text: "Research Log"
        file: ./research/index.qmd

      # - text: "Spatial SQL"
      #   file: ./Spatial SQL/index.qmd
      # - text: "Policy Analysis"
      #   file: ./Policy Analysis/index.qmd 
      # - text: "Statistics"
      #   file: ./Statistics/index.qmd
      # - text: "Visualizations"
      #   file: ./Visualizations/index.qmd 
    tools:
    - icon: github
      href: https://github.com/gigisung0503/
    - icon: linkedin
      href: https://linkedin.com/in/gigisung

    right:
      - icon: rss
        href: research/index.xml


  sidebar:
      - title: "Projects"
        style: "docked"
        background: '#FFFFFF'
        # contents:
        #   section: Projects/index.qmd
        #   contents:
        #     - section: "Climate Mitigation"
        #       contents:
        #         - ./Projects/energy/microgrids.md
        #     - section: "Climate Adaptation"
        #       contents:
        #         - ./Projects/adaptation/bos_uhi.ipynb 
        #         - ./Projects/adaptation/sovi_svi.ipynb
        #     - section: "Analytics"
        #       contents:
        #         - ./Projects/analytics/spaceX.qmd 
        #     - section: "Digital Transformation"
        #       contents:
        #         - ./Projects/dx/digital_twins.md

      - title: "Spatial SQL"
        contents:
          section: Spatial SQL/index.qmd
          contents:
            - ./Spatial SQL/setting_up_db.md
            - ./Spatial SQL/raster_function.md

      - title: "Policy Analysis"
        contents:
          section: Policy Analysis/index.qmd
          contents:
            - section: "Chapter 1: TOD"
              contents:
                - ./Policy Analysis/Chapter1/TOD.qmd
            - section: "Chapter 2: Energy"
              contents:
                - ./Policy Analysis/Chapter2/energy.qmd
                - ./Policy Analysis/Chapter2/reference.md
            - section: "Chapter 3: Land Use"
              contents:
                # - ./Policy Analysis/Chapter3/Zoning.qmd
            - section: "Chapter 4: Housing"
              contents:
                # - ./Policy Analysis/Chapter4/Transportation.qmd
            - section: "Chapter 5: Climate"
              # contents:
              #   - ./Policy Analysis/Chapter5/Climate.qmd
            
          

      # - title: "Visualizations"
      #   contents:
      #     section: Visualizations/index.qmd
      #     contents:
      #       - ./Work in Progress/mapping_uncertainty.ipynb
          


  # sidebar:
  #   # logo: "images/boston.png"
  #   pinned: true
  #   align: center
  #   tools: 
  #     - icon: globe
  #       href: https://gigisung0503.github.com
  #       text: "GitHub"
  #     - icon: github
  #       href: https://github.com/gigisung0503/
  #       text: "MUSA 550 GitHub"
  #     - icon: linkedin
  #       href: https://linkedin.com/in/gigisung
  #       text: "LinkedIn"         

  #   style: "floating"
  #   search: true
  #   collapse-level: 2
  #   contents:
  #     - href: index.qmd
  #       text: Welcome
  #     - about.qmd
  #     - section: Projects/index.qmd
  #       contents:
  #         - Projects/bos_uhi.ipynb 
  #         - Projects/sovi_svi.ipynb
  #     - section: Spatial SQL/index.qmd
  #       contents:
  #         - Spatial SQL/setting_up_db.md
  #         - Spatial SQL/raster_function.md
  #     - section: Work in Progress/index.qmd
  #       contents:
  #         - Work in Progress/mapping_uncertainty.ipynb 

format:
  html:
    # page-layout: full
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true



