project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Gigi Ji Yeon Sung's Workspace"
  site-url: "https://gigisung0503.github.io/" 
  repo-url: https://github.com/gigisung0503/ 
  repo-actions: [source]

  page-footer:
    right: "All rights reserved. 2024."
    left: "&copy; CC-Gigi Sung, 2024"

  sidebar:
    logo: "images/boston.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://gigisung0503.github.com
        text: "GitHub"
      - icon: github
        href: https://github.com/gigisung0503/
        text: "MUSA 550 GitHub"
      - icon: linkedin
        href: https://linkedin.com/in/gigisung
        text: "LinkedIn"         

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: Topical/index.qmd
        contents:
          - Topical/bos_uhi.ipynb 
          - Topical/2-static-images.ipynb
          - Topical/3-altair-hvplot.ipynb
          - Topical/4-folium.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




