project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Gigi Ji Yeon Sung's Workspace"
  site-url: "https://gigisung0503.github.io/" 
  repo-url: https://github.com/gigisung0503/gigisung0503.github.io.git
  repo-actions: [source]

  page-footer:
    right: "All rights reserved. 2024."
    left: "&copy; CC-Gigi Sung, 2024"

  sidebar:
    logo: "images/boston.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://gigisung0503.github.com
        text: "GitHub"
      - icon: github
        href: https://github.com/gigisung0503/
        text: "MUSA 550 GitHub"
      - icon: linkedin
        href: https://linkedin.com/in/gigisung
        text: "LinkedIn"         

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: Topical/index.qmd
        contents:
          - Topical/bos_uhi.ipynb 
          - Topical/sovi_svi.ipynb
      - section: Spatial SQL/index.qmd
        contents:
          - Spatial SQL/setting_up_db.md
          - Spatial SQL/raster_function.md
      - section: Work in Progress/index.qmd
        contents:
          - Work in Progress/mapping_uncertainty.ipynb 

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




